# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  cbor_metadata = false
  # https://docs.soliditylang.org/en/latest/using-the-compiler.html#target-options
  evm_version = "prague"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  solc = "0.8.29"
  src = "contracts"
  libs = ["dependencies"]
  test = "foundry/test"
  script = "foundry/script"
  out = "foundry/out"
  broadcast = 'foundry/broadcast'
  cache_path = 'foundry/cache'


[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  arbitrum_one = { key = "${API_KEY_ARBISCAN}" }
  avalanche = { key = "${API_KEY_SNOWTRACE}" }
  bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
  gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
  goerli = { key = "${API_KEY_ETHERSCAN}" }
  optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  polygon = { key = "${API_KEY_POLYGONSCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"

  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  goerli  = "https://eth-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  holesky = "https://ethereum-holesky.publicnode.com"

  morph = "https://rpc-quicknode.morphl2.io"

  polygon = "https://polygon-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  mumbai  = "https://polygon-mumbai.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

  base_mainnet = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base_goerli  = "https://base-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

  arbitrum_mainnet = "https://arb-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  arbitrum_goerli  = "https://arb-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

  optimism_mainnet = "https://opt-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  optimism_goerli  = "https://opt-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

  avalanche_mainnet = "https://avax-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  avalanche_fuji = "https://rpc.ankr.com/avalanche_fuji"

# https://soldeer.xyz/
[dependencies]
"forge-std" = { version = "1.9.6", git = "https://github.com/foundry-rs/forge-std.git", rev = "6853b9ec7df5dc0c213b05ae67785ad4f4baa0ea" }
"@openzeppelin-contracts" = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
# a prefix to add to the remappings ("@" would give `@name`)
remappings_prefix = ""
# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"
